Incorrectly init as an object instead of array
When adding an account, the following error was being thrown on a newly initialised environment:

Traceback (most recent call last):
  File "/usr/local/lib/aws-creds/run.py", line 17, in <module>
    method()
  File "/usr/local/lib/aws-creds/ui.py", line 26, in add
    return cred.add(cred_config)
  File "/usr/local/lib/aws-creds/cred.py", line 26, in add
    existing_accounts.append(cred_config)
AttributeError: 'dict' object has no attribute 'append'

This has been resolved by updating the accounts.json init code.